# Generated by Django 3.2.6 on 2021-08-14 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_designer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='top_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
